// lib/projects.js
// Single source of truth — import this anywhere

export const allProjects = [
  // ── DESIGN PROJECTS ──
  {
    slug: "al-noor-mixed-use-tower",
    category: "design",
    title: "Al Noor Mixed-Use Tower",
    type: "Architectural Design",
    location: "Riyadh, Saudi Arabia",
    year: "2025",
    area: "42,000 sq ft",
    status: "In Progress",
    client: "Al Noor Holdings",
    clientRole: "Developer",
    duration: "18 months",
    scope:
      "Full architectural design, façade development, authority submissions, and construction documentation for a 14-storey mixed-use tower.",
    coverImg: "/images/hero-bg.webp",
    images: [
      { src: "/images/hero-bg.webp", label: "View 1 — Exterior Render" },
      { src: "/images/hero-bg.webp", label: "View 2 — Lobby Level" },
      { src: "/images/hero-bg.webp", label: "View 3 — Typical Floor Plan" },
      { src: "/images/hero-bg.webp", label: "View 4 — Façade Detail" },
    ],
  },
  {
    slug: "executive-office-suite",
    category: "design",
    title: "Executive Office Suite",
    type: "Interior Design",
    location: "Lahore, Pakistan",
    year: "2024",
    area: "3,200 sq ft",
    status: "Completed",
    client: "Private Corporate Client",
    clientRole: "End User",
    duration: "4 months",
    scope:
      "Full interior design and fit-out of an executive office suite including space planning, bespoke joinery, lighting design, and material specification.",
    coverImg: "/images/hero-bg.webp",
    images: [
      { src: "/images/hero-bg.webp", label: "View 1 — Executive Office" },
      { src: "/images/hero-bg.webp", label: "View 2 — Boardroom" },
      { src: "/images/hero-bg.webp", label: "View 3 — Reception" },
    ],
  },
  {
    slug: "seaside-villa-phase-ii",
    category: "design",
    title: "Seaside Villa — Phase II",
    type: "Architectural Design",
    location: "DHA, Karachi",
    year: "2025",
    area: "5,800 sq ft",
    status: "In Progress",
    client: "Private Residence",
    clientRole: "Homeowner",
    duration: "8 months",
    scope:
      "Extension and remodel of an existing seafront villa — new guest wing, rooftop terrace, and full façade redesign.",
    coverImg: "/images/hero-bg.webp",
    images: [
      { src: "/images/hero-bg.webp", label: "View 1 — Exterior" },
      { src: "/images/hero-bg.webp", label: "View 2 — Rooftop Terrace" },
      { src: "/images/hero-bg.webp", label: "View 3 — Guest Wing" },
      { src: "/images/hero-bg.webp", label: "View 4 — Pool Area" },
    ],
  },
  {
    slug: "gulberg-corporate-hq",
    category: "design",
    title: "Gulberg Corporate HQ",
    type: "Interior Design",
    location: "Lahore, Pakistan",
    year: "2025",
    area: "8,400 sq ft",
    status: "In Progress",
    client: "Confidential",
    clientRole: "Corporate Client",
    duration: "6 months",
    scope:
      "Interior fit-out of a corporate HQ across two floors — executive suites, open-plan workspaces, boardroom, and reception area.",
    coverImg: "/images/hero-bg.webp",
    images: [
      { src: "/images/hero-bg.webp", label: "View 1 — Open Plan" },
      { src: "/images/hero-bg.webp", label: "View 2 — Boardroom" },
    ],
  },
  {
    slug: "f11-boutique-residences",
    category: "design",
    title: "F-11 Boutique Residences",
    type: "3D Visualization",
    location: "Islamabad, Pakistan",
    year: "2025",
    area: "18,200 sq ft",
    status: "Concept Stage",
    client: "Private Developer",
    clientRole: "Developer",
    duration: "12 months",
    scope:
      "Architectural concept design and full 3D visualization for a boutique residential development of eight premium apartments.",
    coverImg: "/images/hero-bg.webp",
    images: [
      { src: "/images/hero-bg.webp", label: "View 1 — Exterior Render" },
      { src: "/images/hero-bg.webp", label: "View 2 — Lobby Concept" },
      { src: "/images/hero-bg.webp", label: "View 3 — Unit Interior" },
    ],
  },

  // ── CONSTRUCTION PROJECTS ──
  {
    slug: "dha-residential-villa",
    category: "construction",
    title: "Residential Villa — DHA Phase 5",
    type: "Turnkey Construction",
    location: "Lahore, Pakistan",
    year: "2024",
    area: "4,200 sq ft",
    status: "Completed",
    client: "Private Family",
    clientRole: "Homeowner",
    duration: "14 months",
    scope:
      "Complete turnkey construction including grey structure, MEP, finishing works, landscaping, and interior fit-out.",
    coverImg: "/images/hero-bg.webp",
    images: [
      { src: "/images/hero-bg.webp", label: "View 1 — Front Elevation" },
      { src: "/images/hero-bg.webp", label: "View 2 — Living Area" },
      { src: "/images/hero-bg.webp", label: "View 3 — Kitchen" },
      { src: "/images/hero-bg.webp", label: "View 4 — Garden" },
    ],
  },
  {
    slug: "blue-area-commercial-plaza",
    category: "construction",
    title: "Commercial Plaza — Blue Area",
    type: "Grey Structure & Finishing",
    location: "Islamabad, Pakistan",
    year: "2023",
    area: "28,000 sq ft",
    status: "Completed",
    client: "Blue Area Developers",
    clientRole: "Developer",
    duration: "20 months",
    scope:
      "Full construction of a mixed-use commercial plaza including grey structure, MEP coordination, and complete finishing works.",
    coverImg: "/images/hero-bg.webp",
    images: [
      { src: "/images/hero-bg.webp", label: "View 1 — Exterior" },
      { src: "/images/hero-bg.webp", label: "View 2 — Ground Floor" },
      { src: "/images/hero-bg.webp", label: "View 3 — Atrium" },
    ],
  },
  {
    slug: "cafe-retail-fitout",
    category: "construction",
    title: "Café & Retail Fit-Out",
    type: "Interior Fit-Out",
    location: "Lahore, Pakistan",
    year: "2024",
    area: "900 sq ft",
    status: "Completed",
    client: "F&B Operator",
    clientRole: "Business Owner",
    duration: "6 weeks",
    scope: "High-speed interior fit-out — fluted timber walls, concrete counters, custom pendant lighting, and MEP.",
    coverImg: "/images/hero-bg.webp",
    images: [
      { src: "/images/hero-bg.webp", label: "View 1 — Counter Area" },
      { src: "/images/hero-bg.webp", label: "View 2 — Seating Zone" },
    ],
  },
  {
    slug: "warehouse-factory-karachi",
    category: "construction",
    title: "Warehouse & Factory Building",
    type: "Industrial Construction",
    location: "Karachi, Pakistan",
    year: "2023",
    area: "32,000 sq ft",
    status: "Completed",
    client: "Manufacturing Client",
    clientRole: "Business Owner",
    duration: "10 months",
    scope:
      "Design and construction of an industrial warehouse and factory facility including foundations, structural steel, and utility services.",
    coverImg: "/images/hero-bg.webp",
    images: [
      { src: "/images/hero-bg.webp", label: "View 1 — Exterior" },
      { src: "/images/hero-bg.webp", label: "View 2 — Interior Hall" },
    ],
  },
  {
    slug: "private-residence-renovation",
    category: "construction",
    title: "Private Residence Renovation",
    type: "Renovation & MEP",
    location: "Rawalpindi, Pakistan",
    year: "2024",
    area: "2,800 sq ft",
    status: "Completed",
    client: "Private Family",
    clientRole: "Homeowner",
    duration: "3 months",
    scope:
      "Full home renovation including structural modifications, complete replumbing, electrical rewiring, and new interior finishes.",
    coverImg: "/images/hero-bg.webp",
    images: [
      { src: "/images/hero-bg.webp", label: "View 1 — Living Room" },
      { src: "/images/hero-bg.webp", label: "View 2 — Master Bedroom" },
      { src: "/images/hero-bg.webp", label: "View 3 — Kitchen" },
    ],
  },
];

export const ongoingProjects = [
  {
    id: "01",
    title: "Al Noor Mixed-Use Tower",
    type: "Design & Build",
    location: "Riyadh, Saudi Arabia",
    started: "Jan 2025",
    eta: "Dec 2025",
    progress: 38,
    area: "42,000 sq ft",
    status: "Design Development",
    statusColor: "bg-sand-200 text-wood-800",
    desc: "A 14-storey mixed-use development combining ground-floor retail, serviced offices, and residential floors. Currently in design development with structural coordination underway.",
    milestones: [
      "Brief & Feasibility",
      "Concept Design",
      "Design Development",
      "Authority Submission",
      "Construction",
      "Handover",
    ],
    activeMilestone: 2,
    img: "/images/hero-bg.webp",
    accent: "#a97040",
  },
  {
    id: "02",
    title: "Gulberg Corporate HQ",
    type: "Interior Design",
    location: "Lahore, Pakistan",
    started: "Mar 2025",
    eta: "Aug 2025",
    progress: 65,
    area: "8,400 sq ft",
    status: "On Site",
    statusColor: "bg-forest-100 text-forest-800",
    desc: "Full interior fit-out of a corporate headquarters across two floors — executive suites, open-plan workspaces, boardroom, and reception. Joinery and finishes currently being installed.",
    milestones: [
      "Brief & Feasibility",
      "Concept Design",
      "Design Development",
      "BOQ & Procurement",
      "Site Execution",
      "Handover",
    ],
    activeMilestone: 4,
    img: "/images/hero-bg.webp",
    accent: "#437f47",
  },
  {
    id: "03",
    title: "Seaside Villa — Phase II",
    type: "Architectural Design",
    location: "DHA, Karachi",
    started: "Feb 2025",
    eta: "Oct 2025",
    progress: 22,
    area: "5,800 sq ft",
    status: "Authority Submission",
    statusColor: "bg-wood-100 text-wood-700",
    desc: "Extension and remodel of an existing seafront villa — new guest wing, rooftop terrace, and façade redesign. Authority submission drawings currently being reviewed.",
    milestones: [
      "Brief & Feasibility",
      "Concept Design",
      "Authority Submission",
      "Construction Drawings",
      "Construction",
      "Handover",
    ],
    activeMilestone: 2,
    img: "/images/hero-bg.webp",
    accent: "#8f5a34",
  },
  {
    id: "04",
    title: "F-11 Boutique Residences",
    type: "Design & Build",
    location: "Islamabad, Pakistan",
    started: "Apr 2025",
    eta: "Mar 2026",
    progress: 12,
    area: "18,200 sq ft",
    status: "Concept Stage",
    statusColor: "bg-sand-100 text-sand-800",
    desc: "A boutique residential development of eight premium apartments with shared amenities. Concept design approved; entering design development and structural brief.",
    milestones: [
      "Brief & Feasibility",
      "Concept Design",
      "Design Development",
      "BOQ & Tender",
      "Construction",
      "Handover",
    ],
    activeMilestone: 2,
    img: "/images/hero-bg.webp",
    accent: "#bc8a57",
  },
];

export function getProjectBySlug(slug) {
  return allProjects.find((p) => p.slug === slug) || null;
}

export function getDesignProjects() {
  return allProjects.filter((p) => p.category === "design");
}

export function getConstructionProjects() {
  return allProjects.filter((p) => p.category === "construction");
}
